### ISSUE TITLE
Add tests 

### ISSUE THREAD

**Issue by CuriousChum** [Andrew-Kwok/csc207-bermuda#36]
Add tests to test the code. Need unit tests and e2e tests.

**Comment by Andrew-Kwok** [comment]
Testing is completed in 
- https://github.com/Andrew-Kwok/csc207-bermuda/pull/57
- https://github.com/Andrew-Kwok/csc207-bermuda/pull/58
- https://github.com/Andrew-Kwok/csc207-bermuda/pull/61
- https://github.com/Andrew-Kwok/csc207-bermuda/pull/64
- https://github.com/Andrew-Kwok/csc207-bermuda/pull/65
- https://github.com/Andrew-Kwok/csc207-bermuda/pull/66
- https://github.com/Andrew-Kwok/csc207-bermuda/pull/68
